language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
notifications:
  email:
    recipients:
      - m@m-jo.co
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
